### ISSUE TITLE
things that confusing me a bit 

### ISSUE THREAD

**Issue by SoonyangZhang** [ASPLes/myqtt#1]
I have read the open mqtt stack of myqtt. But there is something which make me feel confused.(case MYQTT_PUBLISH:
        /\* handle PUBLISH packet */
        __myqtt_reader_async_run (conn, msg, __myqtt_reader_handle_publish, axl_false);). It seem the function just publishes message to the specific connection. But which function deals to find the subscribers which subs the topic and publish message to those connections?

**Comment by francisbrosnan** [comment]
Hello there,
Keep on reading in that function. A few lines after there is a call to __myqtt_reader_initiate_onward_delivery which in turns calls to __myqtt_reader_do_publish at some point.
Best Regards,
